name: Vercel Preview URL Lighthouse Audit

on:
  issue_comment:
    types: [created, edited]

jobs:
  generate_lighthouse_audit:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - name: Add comment to PR
        id: loading_comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.issue.number }}
          header: lighthouse
          message: |
            Running Lighthouse audit...
<<<<<<< HEAD

=======
>>>>>>> 75f6a77 (don't make lighthouse comment if vercel_url not found)
      - name: Get Vercel preview URL
        id: get_preview_url
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment;
            const regex = /https:\/\/[a-z0-9-]+\.vercel\.app/g;
            const matches = comment.body.match(regex);
            let previewUrl = "";
            if (matches && matches.length) {
              previewUrl = matches[0];
              console.log('Preview url found:', previewUrl);
            }
            console.log("No preview url found.");
            core.setOutput('vercel_preview_url', previewUrl);
            
      - name: Add comment to PR
        if: ${{ steps.get_preview_url.outputs.vercel_preview_url != '' }}
        id: loading_comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.issue.number }}
          header: lighthouse
          message: |
            Running Lighthouse audit...

      - name: Checkout repository
        if: ${{ steps.get_preview_url.outputs.vercel_preview_url != '' }}
        uses: actions/checkout@v3

=======
      - name: Get Vercel preview URL
        id: get_preview_url
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment;
            console.log(comment);
            const regex = /https:\/\/[a-z0-9-]+\.vercel\.app/g;
            console.log(regex);
            const previewUrl = comment.body.match(regex)[0];
            console.log(previewUrl);
            core.setOutput('vercel-preview-url', previewUrl);

      - uses: actions/checkout@v3
>>>>>>> fbae7d7 (fix: get preview url (#438))
      - name: Audit preview URL with Lighthouse
        if: ${{ steps.get_preview_url.outputs.vercel_preview_url != '' }}
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ steps.get_preview_url.outputs.vercel_preview_url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
      - name: Format lighthouse score
        if: ${{ steps.get_preview_url.outputs.vercel_preview_url != '' }}
        id: format_lighthouse_score
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const result = ${{ steps.lighthouse_audit.outputs.manifest }}[0].summary
            const links = ${{ steps.lighthouse_audit.outputs.links }}

            const formatResult = (res) => Math.round((res * 100))
            Object.keys(result).forEach(key => result[key] = formatResult(result[key]))

            const score = res => res >= 90 ? '🟢' : res >= 50 ? '🟠' : '🔴'

            const comment = [
                `⚡️ [Lighthouse report](${Object.values(links)[0]}) for the changes in this PR:`,
                '| Category | Score |',
                '| --- | --- |',
                `| ${score(result.performance)} Performance | ${result.performance} |`,
                `| ${score(result.accessibility)} Accessibility | ${result.accessibility} |`,
                `| ${score(result['best-practices'])} Best practices | ${result['best-practices']} |`,
                `| ${score(result.seo)} SEO | ${result.seo} |`,
                `| ${score(result.pwa)} PWA | ${result.pwa} |`,
                ' ',
                `*Lighthouse ran on [${Object.keys(links)[0]}](${Object.keys(links)[0]})*`
            ].join('\n')

             core.setOutput("comment", comment);
             
      - name: Add comment to PR
        if: ${{ steps.get_preview_url.outputs.vercel_preview_url != '' }}
        id: comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.issue.number }}
          header: lighthouse
          message: |
            ${{ steps.format_lighthouse_score.outputs.comment }}
